### ISSUE TITLE
Update for raven-php 0.10.0

### ISSUE THREAD

**Issue by dbanck** [crisu83/yii-sentry#5]
This extension requires raven-php 0.8.0, but the current version of raven-php is 0.10.0.

**Comment by crisu83** [comment]
@kryysler can you please update the raven version when you have time. Thanks!

**Comment by motin** [comment]
The current version of raven is now 0.13.0 and this has not yet been updated. What about instead specifying 0.* as the version requirement and only lock it down when there is a reported breakage?
